name: "Feat"
description: "feat 작업 시 입력해주세요."
labels: [feat]
title: "feat: "
body:
  - type: input
    id: branch
    attributes:
      label: "브랜치 이름은 무엇인가요?"
      description: "브랜치 생성을 원치 않으면 비워두세요."
      placeholder: "chat-service"
    validations:
      required: false
  - type: input
    id: description
    attributes:
      label: "작업할 내용은 무엇인가요?"
      description: "기능에 대해 간략히 설명해주세요."
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "할 일은 무엇인가요?"
      description: "해당 이슈에 대해 필요한 작업목록을 작성해주세요."
      value: |
        - [ ]
    validations:
      required: true

  - type: checkboxes
    id: without_jira_issue
    attributes:
      label: "지라 이슈를 제외할까요?"
      description: "체크하면 지라 이슈와 티켓 넘버가 생성되지 않아요."
      options:
        - label: 지라 이슈를 만들지 않을래요

  - type: input
    id: due_date
    attributes:
      label: "개발 기한은 언제인가요?"
      description: "비워두시면 다음날로 저장할게요."
      placeholder: "YYYY-MM-DD"
    validations:
      required: false
